---
title: "R map creation screencast"
author: "Birasafab"
date: "2023-06-25"
output: html_document
editor_options: 
  chunk_output_type: console
---

# loading all the required packages
```{r}
library(tidyverse)

map_data('world') %>% 
  ggplot(aes(x = long,y= lat,group=group))+
  geom_polygon(fill= 'green')+
  ggthemes::theme_map()
```

# Map of the East African community countries
```{r}
map_data('world') %>% 
  filter(region %in% c('Rwanda','Burundi','Kenya','Tanzania','Uganda','South Sudan','Democratic Republic of the Congo')) %>% 
  ggplot(aes(x = long,y= lat,group=group,fill = region))+
  geom_polygon()+
  ggthemes::theme_map()+
  theme(legend.position = 'top')+
  labs(title = "East African community map",
       subtitle = 'this is the map of the east africa containing all the countries currently members of the EAC including DR CONGO')
  
```

# creating continent map
```{r}
# loading the countrycode package
library(countrycode)

# creating country codes
continent_data = map_data('world') %>% 
  mutate(count_code = countrycode(region,origin = 'country.name',destination = 'iso3c')) %>% 
  # combining the above map_data with codelist data (continent and iso3c)
  left_join(codelist %>% select(continent, iso3c), by = c('count_code'='iso3c'))%>%
  # removing all the countries/areas without iso3_code
  filter(!is.na(count_code))
```

# reading the UN population prospects as of 2020
```{r}
# loading a package to read excel files
library(readxl)

countries_data = 
  read_excel("WPP2022_GEN_F01_DEMOGRAPHIC_INDICATORS_REV1.xlsx",sheet = "Estimates",skip = 16, col_types = 'text') %>% 
  janitor::clean_names() %>% 
  select(region = "region_subregion_country_or_area", year, total = "total_population_as_of_1_january_thousands", iso3c = "iso3_alpha_code") %>% 
  mutate(region = str_to_lower(region)) %>% 
  filter(region != 'world' & !is.na(year) & year == 2020)


# merging continents map geolocation data with world population prospects data

final_data = continent_data %>% 
  left_join(countries_data, by = c("count_code" = "iso3c")) %>% 
  mutate(total = as.numeric(total))
  
```


# creating the continent specific map
```{r}
continent_data %>%
  filter(continent == 'Africa' & !is.na(count_code)) %>% 
  ggplot(aes(long,lat,group=group, fill = region))+
  ggthemes::theme_map()+
  geom_polygon()+
  theme(legend.position = 'None')
```

# African population data map
```{r}
final_data %>% 
  filter(continent == 'Africa') %>% 
  ggplot(aes(long,lat, group = group, fill = total))+
  geom_polygon()+
  ggthemes::theme_map()+
  labs(title = 'African population prospects as of 2020',
       fill = 'Population size',
       subtitle = 'Only Nigeria has above 200 million population \nFollowed with Ethiopia having almost 115',
       caption = "Plot by Birasafab | #30daysChartChallenge")+
  theme(panel.background = element_rect('#add8e6'),
        plot.background = element_rect('#eab676'),
        legend.background = element_blank())+
  scale_fill_gradient(high = "#f3ec27",low = "#300790")

ggsave(filename = 'African population size map 2020.png', device = 'png')
```


# creating the continent specific map - --- World population prospects
```{r}
final_data %>%
  filter(continent == 'Africa' & !is.na(count_code)) %>% 
  ggplot(aes(long,lat,group=group, fill = total_pop_000))+
  ggthemes::theme_map()+
  geom_polygon()+
  labs(
    title = 'Population size in Africa as of 2020',
    fill = 'Population size'
  )+
  theme(panel.background = element_rect(fill='#add8e6'),
                                        plot.background = element_rect(fill='#eab676'),
        legend.background = element_blank())+
 # guides(fill = guide_legend(labels = comma))+
scale_fill_gradient2(high = 'red',low = 'blue',midpoint = 100000)+
  scale_colour_continuous(formatter = comma) 
  scale_fill_continuous(labels =paste0(c('0','50','100','150','200'),',000,000'))
```
