---
title: "draft"
author: "Birasafab"
date: "2023-07-06"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

# creating a geom_point graph
```{r}
p1 = mpg %>% 
  ggplot(aes(displ,cty))+
  geom_point()

# creating a geom_smooth plot
p2 = mpg %>% 
  ggplot(aes(displ,cty))+
  geom_smooth()

# combining two or multiple ggplot chart using ggpubr package
ggpubr::ggarrange(p1,p2)

mpg %>% 
  ggplot(aes(drv,cyl))+
  geom_point()
```

# an alternative way to create bar charts
```{r}
bar_data <- tribble(
  ~cut,         ~freq,
  "Fair",       1610,
  "Good",       4906,
  "Very Good",  12082,
  "Premium",    13791,
  "Ideal",      21551
)


bar_data %>% 
  mutate(cut = fct_reorder(cut,freq)) %>% 
ggplot() +
  geom_bar(mapping = aes(x = cut, y = freq, fill = cut), stat = "identity")+
  # rotating the axis text
  theme(axis.text.x = element_text(angle = 40))
```

# creating bars with additional aesthetic column for color
```{r}
diamonds %>% 
  ggplot()+
  geom_bar(aes(cut, fill = clarity), position = 'fill')
```

# How to avoid points overlapping within geom_point?
```{r}
mpg %>% 
  ggplot(aes(hwy,displ))+
  geom_point(position = 'jitter')+
  geom_smooth()
```

# Data Transformation
```{r}
library(nycflights13)

```

# Flights data transformation by using flights data
```{r}
# combining flights data with airlines one
flights %>% 
  left_join(airlines, by = c(carrier = 'carrier')) %>% view()


# finding all the flights which departed on First January.
flights %>% 
  filter(month ==1 & day==1)

# finding all the flights that departed in November or december

flights %>% 
  filter(month %in% c(11,12)) %>% distinct(month)

## or we can use the following code

flights %>% 
  filter(month==11 | month==12) %>% distinct(month)
```

